#!/bin/bash

# scp xixiaw@cycles.cs.princeton.edu:/n/fs/chinese-pcfg/password_types.txt .
# scp xixiaw@cycles.cs.princeton.edu:/n/fs/chinese-pcfg/70yx_samp.txt .
# scp xixiaw@cycles.cs.princeton.edu:/n/fs/chinese-pcfg/done_* .
# scp xixiaw@cycles.cs.princeton.edu:/n/fs/chinese-pcfg/70yx_samp*.txt .
# scp xixiaw@cycles.cs.princeton.edu:/n/fs/chinese-pcfg/70yx_cor_train.txt .
# scp xixiaw@cycles.cs.princeton.edu:/n/fs/chinese-pcfg/samp_*.txt .

# scp xixiaw@cycles.cs.princeton.edu:/n/fs/chinese-pcfg/70yx_pinyin.txt .
# scp xixiaw@cycles.cs.princeton.edu:/n/fs/chinese-pcfg/70yx_eng.txt .

# scp xixiaw@cycles.cs.princeton.edu:/n/fs/chinese-pcfg/70yx_short_structs.txt .
scp xixiaw@cycles.cs.princeton.edu:/n/fs/chinese-pcfg/csdn_gen_pure.txt .
scp xixiaw@cycles.cs.princeton.edu:/n/fs/chinese-pcfg/csdn_jtr_pure.txt .